### Library loading

library(Seurat)
library(SeuratData)
library(SeuratWrappers)
library(ggplot2)
library(SeuratDisk)
library(kBET)
library(aricode)
library(magrittr)
library(factoextra)
library(lisi)
library(monocle3)
library(pls)
library(cluster)
library(slingshot)
library(destiny)
library(TSCAN)